trigger:
  branches:
    include:
      - master

variables:
- group: ACR-SP-Variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Build and push the Docker image using Azure CLI (service principal now has AcrPush permission)
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MicroService_Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logging in to ACR..."
      az acr login --name $(ACR_NAME)

      IMAGE_TAG="$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)"
      echo "Building and pushing $IMAGE_TAG"

      docker build -t $IMAGE_TAG .
      docker push $IMAGE_TAG

