trigger:
  branches:
    include:
      - master

variables:
- group: ACR-SP-Variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Login to ACR
- task: Docker@2
  inputs:
    command: login
    containerRegistry: MicroService_Connection

# Build and push the Docker image to ACR
- task: Docker@2
  inputs:
    command: buildAndPush
    containerRegistry: MicroService_Connection
    repository: $(IMAGE_NAME)
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
