trigger:
  branches:
    include:
      - master

variables:
- group: ACR-SP-Variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MicroService_Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Get ACR token when using service principal
      TOKEN=$(az acr login --name $(ACR_NAME) --expose-token --output tsv --query accessToken)

      echo "Logging into ACR with docker login"
      echo $TOKEN | docker login $(ACR_NAME).azurecr.io -u 00000000-0000-0000-0000-000000000000 --password-stdin

      IMAGE_TAG="$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)"
      echo "Building and pushing $IMAGE_TAG"
      docker build -t $IMAGE_TAG .
      docker push $IMAGE_TAG
